cells = []
CELLCOUNT = 14

CELL_DISCOVER_COLOR = (.9,.9,.9,1)
CELL_BOMB_COLOR = (.8,.2,.2,1)

MAIN_INTERFACE_SPACE = 3

LAYOUT_CHANGE_BREAK_POINT = 0.87

VERTICAL_SCROLL_VIEW_MAX_HEIGHT = 700
VERTICAL_SCROLL_VIEW_MIN_HEIGHT = 400

HORIZONTAL_LABEL_MIN_WIDTH = 100

PARTICLE_COUNT = 100

DIALOG_POSSIBILITY = 0.0008