OverLayHandler:

<OverLayHandler@RelativeLayout>:
    MainLayout:
        size_hint: 1,1

<MainLayout>:
    massage_label:massage_label
    Label:
        text: "score: 11113"
        size_hint: 1, None
        height: "50dp"
        id: massage_label
    ScrollView:
        GridDisplay:
            id: Grid
            size_hint: 1, None
            height: self.width

<GridDisplay>:

<CellButton>:
    background_normal: ""
